version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: jashan_jewellers_db
    env_file:
      - ./backend/src/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1.sql # Run schema on startup
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/2.sql # Seed data after schema
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jashan_jewellers_backend
    env_file:
      - ./backend/src/.env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data: